"""add timestamp column in budget item table

Revision ID: 044a2309a3b6
Revises: 0bc5cc2d0bad
Create Date: 2022-06-16 00:20:53.807681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044a2309a3b6'
down_revision = '0bc5cc2d0bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_budget_item_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_item_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
