"""rename user questions field

Revision ID: 051d5de82399
Revises: 07a73f54cecc
Create Date: 2022-07-17 12:11:54.627574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051d5de82399'
down_revision = '07a73f54cecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suppport_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'support', ['suppport_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suppport_id')

    # ### end Alembic commands ###
