"""remove unique constraint

Revision ID: 2031e85f550f
Revises: b3ceaf632d51
Create Date: 2022-06-22 18:07:00.598510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031e85f550f'
down_revision = 'b3ceaf632d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_name')
        batch_op.create_index(batch_op.f('ix_asset_name'), ['name'], unique=False)

    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_index('ix_budget_item_name')
        batch_op.create_index(batch_op.f('ix_budget_item_name'), ['name'], unique=False)

    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.drop_index('ix_liability_name')
        batch_op.create_index(batch_op.f('ix_liability_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liability_name'))
        batch_op.create_index('ix_liability_name', ['name'], unique=False)

    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_item_name'))
        batch_op.create_index('ix_budget_item_name', ['name'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_name'))
        batch_op.create_index('ix_asset_name', ['name'], unique=False)

    # ### end Alembic commands ###
