"""create all tables

Revision ID: 3dd0e21be146
Revises: 
Create Date: 2022-07-28 22:25:27.889920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd0e21be146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin'))
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_phone', sa.String(length=20), nullable=True),
    sa.Column('delete_account_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support'))
    )
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_username'), ['username'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verification_phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('actual_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_actual_income_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actual_income'))
    )
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actual_income_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_income_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_income_name'), ['name'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_asset_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset'))
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_name'), ['name'], unique=False)

    op.create_table('budget_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_budget_item_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_item'))
    )
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_item_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_item_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_item_name'), ['name'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_expenses_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_name'), ['name'], unique=False)

    op.create_table('help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('support_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['support_id'], ['support.id'], name=op.f('fk_help_support_id_support')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_help_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help'))
    )
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_timestamp'), ['timestamp'], unique=False)

    op.create_table('liability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_liability_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liability'))
    )
    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liability_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_liability_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_liability_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liability_name'))
        batch_op.drop_index(batch_op.f('ix_liability_date'))
        batch_op.drop_index(batch_op.f('ix_liability_amount'))

    op.drop_table('liability')
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_timestamp'))

    op.drop_table('help')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_name'))
        batch_op.drop_index(batch_op.f('ix_expenses_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_amount'))

    op.drop_table('expenses')
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_item_name'))
        batch_op.drop_index(batch_op.f('ix_budget_item_date'))
        batch_op.drop_index(batch_op.f('ix_budget_item_amount'))

    op.drop_table('budget_item')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_name'))
        batch_op.drop_index(batch_op.f('ix_asset_date'))
        batch_op.drop_index(batch_op.f('ix_asset_amount'))

    op.drop_table('asset')
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actual_income_name'))
        batch_op.drop_index(batch_op.f('ix_actual_income_date'))
        batch_op.drop_index(batch_op.f('ix_actual_income_amount'))

    op.drop_table('actual_income')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_username'))
        batch_op.drop_index(batch_op.f('ix_support_email'))

    op.drop_table('support')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    # ### end Alembic commands ###
