"""fix support id column name

Revision ID: 428c62142c74
Revises: d4c7261ecb96
Create Date: 2022-07-19 21:36:15.668368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428c62142c74'
down_revision = 'd4c7261ecb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_help_support_id_support'), 'support', ['support_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_help_support_id_support'), type_='foreignkey')
        batch_op.drop_column('support_id')

    # ### end Alembic commands ###
