"""update asset table

Revision ID: 457e7e791428
Revises: db238de10e2f
Create Date: 2022-06-16 00:50:56.112300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457e7e791428'
down_revision = 'db238de10e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_name'), ['name'], unique=True)

    with op.batch_alter_table('asset_item', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_item_name')

    op.drop_table('asset_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_item', schema=None) as batch_op:
        batch_op.create_index('ix_asset_item_name', ['name'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_name'))
        batch_op.drop_index(batch_op.f('ix_asset_date'))
        batch_op.drop_index(batch_op.f('ix_asset_amount'))

    op.drop_table('asset')
    # ### end Alembic commands ###
