"""new name column in actual income table

Revision ID: 49354d3264e0
Revises: fd4b04b6ef24
Create Date: 2022-06-15 23:47:11.451899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49354d3264e0'
down_revision = 'fd4b04b6ef24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_actual_income_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actual_income_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
