"""delete account status column

Revision ID: 5d408e6fbc24
Revises: a28e974d2643
Create Date: 2022-07-28 20:41:31.694281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d408e6fbc24'
down_revision = 'a28e974d2643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_account_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support', schema=None) as batch_op:
        batch_op.drop_column('delete_account_status')

    # ### end Alembic commands ###
