"""budget item table

Revision ID: 630c4b0e40ad
Revises: 3f8be92d6ff9
Create Date: 2022-06-15 12:37:01.278603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630c4b0e40ad'
down_revision = '3f8be92d6ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_item_name'), 'budget_item', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_item_name'), table_name='budget_item')
    op.drop_table('budget_item')
    # ### end Alembic commands ###
