"""add update column in budget item table

Revision ID: 7edba75b846f
Revises: 044a2309a3b6
Create Date: 2022-06-16 00:23:10.497312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edba75b846f'
down_revision = '044a2309a3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_budget_item_month')
        batch_op.drop_index('ix_budget_item_timestamp')
        batch_op.create_index(batch_op.f('ix_budget_item_date'), ['date'], unique=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_budget_item_date'))
        batch_op.create_index('ix_budget_item_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_budget_item_month', ['month'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
