"""phone number field

Revision ID: 992f7f6ade31
Revises: af967c8b75bb
Create Date: 2022-07-16 22:18:36.169923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992f7f6ade31'
down_revision = 'af967c8b75bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_phone')

    # ### end Alembic commands ###
