"""Remove description field in model

Revision ID: b0144132c34b
Revises: 2031e85f550f
Create Date: 2022-06-27 06:13:05.237856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0144132c34b'
down_revision = '2031e85f550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.drop_index('ix_actual_income_description')
        batch_op.drop_column('description')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_description')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_expenses_description', ['description'], unique=False)

    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_actual_income_description', ['description'], unique=False)

    # ### end Alembic commands ###
