"""update liability table

Revision ID: b3ceaf632d51
Revises: 457e7e791428
Create Date: 2022-06-16 01:01:43.338423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ceaf632d51'
down_revision = '457e7e791428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liability_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_liability_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_liability_name'), ['name'], unique=True)

    with op.batch_alter_table('liability_item', schema=None) as batch_op:
        batch_op.drop_index('ix_liability_item_name')

    op.drop_table('liability_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liability_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liability_item', schema=None) as batch_op:
        batch_op.create_index('ix_liability_item_name', ['name'], unique=False)

    with op.batch_alter_table('liability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liability_name'))
        batch_op.drop_index(batch_op.f('ix_liability_date'))
        batch_op.drop_index(batch_op.f('ix_liability_amount'))

    op.drop_table('liability')
    # ### end Alembic commands ###
