"""add amount column in budget item table

Revision ID: b8d7a8a0d1ad
Revises: 49354d3264e0
Create Date: 2022-06-16 00:13:55.292418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d7a8a0d1ad'
down_revision = '49354d3264e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_budget_item_amount'), ['amount'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_item_amount'))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
