"""Fix column name

Revision ID: d4c7261ecb96
Revises: 051d5de82399
Create Date: 2022-07-19 15:15:04.303823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c7261ecb96'
down_revision = '051d5de82399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'support', ['support_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('support_id')

    # ### end Alembic commands ###
