"""answered column

Revision ID: d65d01ee3293
Revises: f5f90f4fd0d4
Create Date: 2022-07-27 05:43:55.804859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65d01ee3293'
down_revision = 'f5f90f4fd0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help', schema=None) as batch_op:
        batch_op.drop_column('answered')

    # ### end Alembic commands ###
