"""remove year and month columns

Revision ID: fd4b04b6ef24
Revises: 27c14ea88775
Create Date: 2022-06-15 23:20:05.381963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4b04b6ef24'
down_revision = '27c14ea88775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.drop_index('ix_actual_income_month')
        batch_op.drop_index('ix_actual_income_year')
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_actual_income_year', ['year'], unique=False)
        batch_op.create_index('ix_actual_income_month', ['month'], unique=False)

    # ### end Alembic commands ###
